name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.c85bc42b-3303-48ef-9b32-64b439121171}}
          heroku_app_name: api-p7-oc
          heroku_email: rim_delage@hotmail.com