name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: test unitaire
        run: |
            pip install unitest
            python -m unittest api_testUnitaire


      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: api-p7-oc
          heroku_email: rim_delage@hotmail.com

      # - name: run to Heroku
      #   run: |
      #     git push heroku main
